// Utility to handle downloading raw text or markdown as files natively via the browser
import type { ReviewSession } from './db';

export function downloadAsMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  
  document.body.appendChild(link);
  link.click();
  
  // Cleanup
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Alias used by ReviewExecution
export const exportAsMarkdown = downloadAsMarkdown;

// Export a rendered HTML element as a PDF using html2pdf.js if available, otherwise window.print()
export function exportAsPDF(element: HTMLElement, options?: { filename?: string }) {
  const filename = options?.filename || 'export.pdf';
  try {
    // Dynamically check for html2pdf
    const html2pdfLib = (window as any).html2pdf;
    if (html2pdfLib) {
      html2pdfLib()
        .set({
          margin: 10,
          filename,
          image: { type: 'jpeg', quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        })
        .from(element)
        .save();
    } else {
      // Fallback: use html2pdf.js ESM import
      import('html2pdf.js').then((mod: any) => {
        const h2p = mod.default || mod;
        (h2p as any)()
          .set({
            margin: 10,
            filename,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2, useCORS: true },
            jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
          })
          .from(element)
          .save();
      }).catch(() => {
        window.print();
      });
    }
  } catch {
    window.print();
  }
}

// In the future this can be expanded to hook up with an HTML to PDF library like html2pdf.js
export function downloadAsPDF(htmlContent: HTMLElement, filename: string) {
    exportAsPDF(htmlContent, { filename });
}

// Generate a full ADR markdown combining session metadata, report, and scorecard
export function generateADRMarkdown(opts: {
  session: ReviewSession;
  reportMarkdown: string;
  scorecardSummary?: string;
  domainName?: string;
}): string {
  const { session, reportMarkdown, scorecardSummary, domainName } = opts;
  const now = new Date().toISOString().split('T')[0];

  let adr = `# Architecture Decision Record (ADR)\n\n`;
  adr += `| Field | Value |\n|-------|-------|\n`;
  adr += `| **Project** | ${session.projectName} |\n`;
  adr += `| **Review Type** | ${session.type} |\n`;
  adr += `| **BIAN Domain** | ${domainName || 'N/A'} |\n`;
  adr += `| **App Tier** | ${session.appTier || 'N/A'} |\n`;
  adr += `| **Hosting Model** | ${session.hostingModel || 'N/A'} |\n`;
  adr += `| **Data Classification** | ${session.dataClassification || 'N/A'} |\n`;
  adr += `| **Status** | ${session.status} |\n`;
  adr += `| **Date** | ${now} |\n\n`;

  if (session.businessJustification) {
    adr += `## Business Justification\n\n${session.businessJustification}\n\n`;
  }

  if (session.humanOverrides?.winningVendorOverride) {
    adr += `## Architecture Board Decision\n\n`;
    adr += `- **Selected Vendor:** ${session.humanOverrides.winningVendorOverride}\n`;
    adr += `- **Justification:** ${session.humanOverrides.justification || 'N/A'}\n`;
    adr += `- **Override Timestamp:** ${session.humanOverrides.overrideTimestamp || 'N/A'}\n\n`;
  }

  if (scorecardSummary) {
    adr += `## BDAT Scorecard Summary\n\n${scorecardSummary}\n\n`;
  }

  adr += `## AI-Generated Review\n\n${reportMarkdown}\n\n`;
  adr += `---\n*Generated by EA-NITI Edge Agent on ${now}*\n`;

  return adr;
}
