/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_sovereigntensorcore_free: (a: number, b: number) => void;
export const main_js: () => void;
export const sovereigntensorcore_allocate_weights_buffer: (a: number, b: number) => [number, number, number];
export const sovereigntensorcore_begin_prefill: (a: number, b: number, c: number) => [number, number, number];
export const sovereigntensorcore_begin_prefill_async: (a: number, b: number, c: number) => any;
export const sovereigntensorcore_clear_kv_cache: (a: number) => void;
export const sovereigntensorcore_compute_epistemic_state: (a: number, b: number, c: number) => [number, number, number, number];
export const sovereigntensorcore_decode_next_token_async: (a: number, b: number, c: number, d: number) => any;
export const sovereigntensorcore_decode_single_token: (a: number, b: number) => [number, number];
export const sovereigntensorcore_free_weights_buffer: (a: number) => void;
export const sovereigntensorcore_generate_next_token: (a: number) => [number, number, number];
export const sovereigntensorcore_generate_next_token_async: (a: number) => any;
export const sovereigntensorcore_get_architecture: (a: number) => [number, number];
export const sovereigntensorcore_get_chat_template: (a: number) => [number, number];
export const sovereigntensorcore_get_eos_id: (a: number) => number;
export const sovereigntensorcore_get_hardware_block_reason: (a: number) => [number, number];
export const sovereigntensorcore_get_tokenizer_model: (a: number) => [number, number];
export const sovereigntensorcore_get_vocab_size: (a: number) => number;
export const sovereigntensorcore_get_vram_max_shard_bytes: (a: number) => number;
export const sovereigntensorcore_get_vram_shard_count: (a: number) => number;
export const sovereigntensorcore_get_vram_upload_status: (a: number) => [number, number];
export const sovereigntensorcore_get_vram_uploaded_bytes: (a: number) => number;
export const sovereigntensorcore_init_webgpu: (a: number) => any;
export const sovereigntensorcore_initialize_tensor_graph: (a: number) => [number, number, number];
export const sovereigntensorcore_is_hybrid_active: (a: number) => number;
export const sovereigntensorcore_is_loaded: (a: number) => number;
export const sovereigntensorcore_is_prefill_complete: (a: number) => number;
export const sovereigntensorcore_is_vram_uploaded: (a: number) => number;
export const sovereigntensorcore_new: () => number;
export const sovereigntensorcore_prefill_next_chunk: (a: number, b: number) => [number, number, number];
export const sovereigntensorcore_prefill_next_chunk_async: (a: number, b: number) => any;
export const sovereigntensorcore_prefill_prompt: (a: number, b: number, c: number) => [number, number];
export const sovereigntensorcore_prefill_prompt_async: (a: number, b: number, c: number, d: number) => any;
export const sovereigntensorcore_reset_generation_state: (a: number) => void;
export const sovereigntensorcore_upload_to_vram: (a: number) => any;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const closure32_externref_shim: (a: number, b: number, c: any) => void;
export const closure27_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
