#!/usr/bin/env node
// bug-runner.mjs — Run the regression suite, capture failures, write bug reports
// Usage: node bug-runner.mjs [--target=prod|dev] [--headed]

import { execSync, spawn } from 'child_process';
import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..', '..');
const REPORT_DIR = join(ROOT, 'test-results', 'e2e', 'reports', 'bugs');
const BACKLOG = join(ROOT, 'BUG_BACKLOG.md');

const args = Object.fromEntries(process.argv.slice(2).map(a => {
  const [k, v] = a.replace(/^--/, '').split('=');
  return [k, v ?? true];
}));

const TARGET = args.target || 'prod';
const HEADED = args.headed || false;

mkdirSync(REPORT_DIR, { recursive: true });

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, '-');
}

function serveTarget(port) {
  return new Promise((resolve, reject) => {
    const serveScript = join(__dirname, 'serve-target.mjs');
    const child = spawn('node', [serveScript, `--target=${TARGET}`, `--port=${port}`], {
      cwd: ROOT,
      stdio: 'pipe',
      env: process.env,
    });

    let ready = false;
    child.stdout.on('data', (data) => {
      const line = data.toString();
      process.stdout.write(line);
      if (line.includes('serving at') || line.includes('ready') || line.includes('Local:')) {
        if (!ready) { ready = true; setTimeout(() => resolve(child), 2000); }
      }
    });
    child.stderr.on('data', (data) => process.stderr.write(data));
    child.on('exit', (code) => { if (!ready) reject(new Error(`Server exited with code ${code}`)); });
    setTimeout(() => { if (!ready) { ready = true; resolve(child); } }, 10000);
  });
}

function runPlaywright(port) {
  const specDir = join(ROOT, 'src', '__tests__', 'e2e', 'regression');
  const headedFlag = HEADED ? '--headed' : '';
  const cmd = `npx playwright test ${specDir} --project=chromium ${headedFlag} --reporter=json --output=test-results/e2e/playwright`;

  console.log(`\nRunning: ${cmd}\n`);
  try {
    const result = execSync(cmd, {
      cwd: ROOT,
      stdio: 'pipe',
      env: { ...process.env, CI: '1' },
      timeout: 600_000,
    });
    return { success: true, output: result.toString() };
  } catch (err) {
    return { success: false, output: err.stdout?.toString() || '', stderr: err.stderr?.toString() || '' };
  }
}

function parseAndWriteBugs(output, runId) {
  let results;
  try {
    const jsonMatch = output.match(/\{[\s\S]*"suites"[\s\S]*\}/);
    if (jsonMatch) results = JSON.parse(jsonMatch[0]);
    else return [];
  } catch {
    return [];
  }

  const bugs = [];
  const suites = results.suites || [];

  for (const suite of suites) {
    for (const spec of suite.specs || []) {
      if (spec.ok) continue;

      for (const test of spec.tests || []) {
        for (const result of test.results || []) {
          if (result.status === 'failed' || result.status === 'timedOut') {
            const bugId = `BUG-${runId}-${bugs.length + 1}`;
            const bug = {
              id: bugId,
              title: spec.title,
              file: spec.file,
              status: result.status,
              duration: result.duration,
              error: result.error?.message || 'No error message',
              attachments: (result.attachments || []).map(a => a.path),
              timestamp: timestamp(),
            };
            bugs.push(bug);
          }
        }
      }
    }
  }

  return bugs;
}

function writeBugReport(bug) {
  const md = `# ${bug.id}: ${bug.title}

**Status:** ${bug.status}
**File:** ${bug.file}
**Timestamp:** ${bug.timestamp}
**Duration:** ${bug.duration}ms

## Error
\`\`\`
${bug.error}
\`\`\`

## Evidence
${bug.attachments.map(a => `- Screenshot: ${a}`).join('\n') || '- No attachments'}

## Repro Steps
1. Navigate to http://localhost:3000
2. Complete standalone auth flow
3. ${bug.title}

---
*Generated by bug-runner.mjs*
`;
  writeFileSync(join(REPORT_DIR, `${bug.id}.md`), md);
  return bug;
}

function updateBacklog(existingBugs, newBugs) {
  const allBugs = [...existingBugs, ...newBugs];
  const md = `# BUG_BACKLOG.md

**Last Updated:** ${timestamp()}
**Total Bugs:** ${allBugs.length}
**Open:** ${allBugs.filter(b => b.status !== 'fixed').length}

## Bugs

| ID | Title | Status | File | Timestamp |
|---|---|---|---|---|
${allBugs.map(b => `| ${b.id} | ${b.title} | ${b.status || 'open'} | ${b.file} | ${b.timestamp} |`).join('\n')}

---
*Auto-updated by bug-runner.mjs*
`;
  writeFileSync(BACKLOG, md);
  return allBugs;
}

// Main
async function main() {
  const PORT = TARGET === 'prod' ? 3000 : 3001;
  console.log(`\n=== Bug Runner ===`);
  console.log(`Target: ${TARGET}`);
  console.log(`Port: ${PORT}`);
  console.log(`Time: ${timestamp()}\n`);

  // Load existing backlog
  let existingBugs = [];
  if (existsSync(BACKLOG)) {
    try {
      const content = readFileSync(BACKLOG, 'utf-8');
      const rows = content.match(/\| BUG-[^|]+/g) || [];
      existingBugs = rows.map(r => {
        const parts = r.split('|').map(s => s.trim()).filter(Boolean);
        return { id: parts[0], title: parts[1], status: parts[2], file: parts[3], timestamp: parts[4] };
      });
    } catch {}
  }

  // Start server
  let server;
  try {
    server = await serveTarget(PORT);
    console.log('Server started');
  } catch (err) {
    console.error('Failed to start server:', err.message);
    process.exit(1);
  }

  // Run playwright
  const { success, output, stderr } = runPlaywright(PORT);
  console.log('\nPlaywright completed:', success ? 'SUCCESS' : 'FAILURES FOUND');

  // Parse bugs
  const runId = timestamp().replace(/T.*/, '');
  const newBugs = parseAndWriteBugs(output + stderr, runId);

  // Write individual bug reports
  for (const bug of newBugs) {
    writeBugReport(bug);
    console.log(`  Bug: ${bug.id} — ${bug.title}`);
  }

  // Update backlog
  const allBugs = updateBacklog(existingBugs, newBugs);

  console.log(`\n=== Summary ===`);
  console.log(`New bugs found: ${newBugs.length}`);
  console.log(`Total bugs: ${allBugs.length}`);
  console.log(`Bug reports: ${REPORT_DIR}`);
  console.log(`Backlog: ${BACKLOG}\n`);

  // Kill server
  if (server) server.kill('SIGTERM');

  process.exit(newBugs.length > 0 ? 1 : 0);
}

main().catch(err => {
  console.error('Fatal:', err);
  process.exit(1);
});
